from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4

from autonomy.types import CandidateStatus, CandidateTarget, MissionObjective, Position, SemanticVisionResult, TargetDetection


class CandidateManager:
    def __init__(self, objective: MissionObjective, log_dir: str = "logs") -> None:
        self.objective = objective
        self.log_dir = Path(log_dir)
        self.log_dir.mkdir(exist_ok=True)
        self.candidates: list[CandidateTarget] = []

    def add_detection(
        self,
        *,
        detection: TargetDetection,
        position: Position | None,
        source: str,
        image_path: str | None = None,
        crop_path: str | None = None,
        explanation: str | None = None,
        semantic_result: SemanticVisionResult | None = None,
    ) -> CandidateTarget | None:
        if not detection.detected:
            return None
        confidence_breakdown = {source: detection.confidence}
        match_score = detection.confidence
        if semantic_result is not None:
            confidence_breakdown[semantic_result.model_name] = semantic_result.score
            match_score = round((detection.confidence * 0.35) + (semantic_result.score * 0.65), 3)
        candidate = CandidateTarget(
            id=str(uuid4()),
            timestamp=datetime.now(timezone.utc).isoformat(),
            position=position,
            source=source,
            match_score=match_score,
            confidence_breakdown=confidence_breakdown,
            explanation=explanation or (
                semantic_result.explanation if semantic_result is not None else "Candidate generated by detector; semantic review pending."
            ),
            semantic_score=None if semantic_result is None else semantic_result.score,
            semantic_decision=None if semantic_result is None else semantic_result.decision,
            semantic_tags=[] if semantic_result is None else semantic_result.tags,
            image_path=image_path,
            crop_path=crop_path,
            bbox=detection.bbox,
            mission_objective=self.objective.raw_request,
        )
        self.candidates.append(candidate)
        self.candidates.sort(key=lambda item: item.match_score, reverse=True)
        return candidate

    def review(self, candidate_id: str, status: CandidateStatus, explanation: str | None = None) -> CandidateTarget:
        candidate = self.get(candidate_id)
        candidate.status = status
        if explanation:
            candidate.explanation = explanation
        return candidate

    def get(self, candidate_id: str) -> CandidateTarget:
        for candidate in self.candidates:
            if candidate.id == candidate_id:
                return candidate
        raise KeyError(f"Candidate not found: {candidate_id}")

    def unreviewed(self) -> list[CandidateTarget]:
        return [candidate for candidate in self.candidates if candidate.status == CandidateStatus.UNREVIEWED]

    def confirmed(self) -> list[CandidateTarget]:
        return [candidate for candidate in self.candidates if candidate.status == CandidateStatus.CONFIRMED]

    def save(self, path: str | Path | None = None) -> Path:
        if path is None:
            stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
            path = self.log_dir / f"candidates_{stamp}.json"
        payload = {
            "objective": asdict(self.objective),
            "candidates": [asdict(candidate) for candidate in self.candidates],
        }
        Path(path).write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
        return Path(path)
